name: Test project-triage

on:
  push:
    branches: ["main"]

jobs:
  test-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test project-triage
        uses: ./ 
        with:
          token: ${{ secrets.PAT_TOKEN }}